### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ethanmci** [ethanmci/IMD4008_A1#1]
- [x] Solution for undefined / infinity from x / 0 problems
- [x] Finish addition + subtraction
- [ ] BigDecimal for possible floating 0 removal
- [x] Get history string working, include formula [extra]
- [x] Add data to bundle so things don't get lost

**Comment by ethanmci** [comment]
dont care about big decimal lol
